import type { Locale } from '@/lib/i18n'
import type { Region } from '@/lib/region'
import type { MediaType } from '@/types/tmdb'

export interface DiscoveryFilters {
  mediaType: MediaType
  genre: number | null
  runtime: number | null
  provider: number | null
  minimumRating: number | null
  sort: 'popular' | 'rated' | 'recent'
}

export const discoveryGenres: Record<MediaType, Array<{ id: number; en: string; ko: string }>> = {
  movie: [
    { id: 28, en: 'Action', ko: '액션' },
    { id: 12, en: 'Adventure', ko: '모험' },
    { id: 16, en: 'Animation', ko: '애니메이션' },
    { id: 35, en: 'Comedy', ko: '코미디' },
    { id: 80, en: 'Crime', ko: '범죄' },
    { id: 99, en: 'Documentary', ko: '다큐멘터리' },
    { id: 18, en: 'Drama', ko: '드라마' },
    { id: 10751, en: 'Family', ko: '가족' },
    { id: 14, en: 'Fantasy', ko: '판타지' },
    { id: 27, en: 'Horror', ko: '공포' },
    { id: 9648, en: 'Mystery', ko: '미스터리' },
    { id: 10749, en: 'Romance', ko: '로맨스' },
    { id: 878, en: 'Science fiction', ko: 'SF' },
    { id: 53, en: 'Thriller', ko: '스릴러' },
  ],
  tv: [
    { id: 10759, en: 'Action & adventure', ko: '액션·모험' },
    { id: 16, en: 'Animation', ko: '애니메이션' },
    { id: 35, en: 'Comedy', ko: '코미디' },
    { id: 80, en: 'Crime', ko: '범죄' },
    { id: 99, en: 'Documentary', ko: '다큐멘터리' },
    { id: 18, en: 'Drama', ko: '드라마' },
    { id: 10751, en: 'Family', ko: '가족' },
    { id: 9648, en: 'Mystery', ko: '미스터리' },
    { id: 10764, en: 'Reality', ko: '리얼리티' },
    { id: 10765, en: 'Sci-fi & fantasy', ko: 'SF·판타지' },
    { id: 10767, en: 'Talk', ko: '토크쇼' },
    { id: 10768, en: 'War & politics', ko: '전쟁·정치' },
  ],
}

export const discoveryProviders: Record<Region, Array<{ id: number; name: string }>> = {
  KR: [
    { id: 8, name: 'Netflix' },
    { id: 337, name: 'Disney+' },
    { id: 350, name: 'Apple TV' },
    { id: 1883, name: 'TVING' },
    { id: 1881, name: 'Coupang Play' },
    { id: 356, name: 'Wavve' },
    { id: 97, name: 'Watcha' },
    { id: 119, name: 'Prime Video' },
  ],
  US: [
    { id: 8, name: 'Netflix' },
    { id: 337, name: 'Disney+' },
    { id: 15, name: 'Hulu' },
    { id: 9, name: 'Prime Video' },
    { id: 350, name: 'Apple TV' },
    { id: 2303, name: 'Paramount+' },
    { id: 1899, name: 'HBO Max' },
    { id: 386, name: 'Peacock' },
  ],
}

export const getDiscoveryCopy = (locale: Locale) => locale === 'ko' ? {
  metadataTitle: '조건으로 작품 찾기',
  metadataDescription: 'OTT, 장르, 러닝타임과 평점을 조합해 오늘 볼 영화와 TV 프로그램을 찾아보세요.',
  eyebrow: '오늘 뭐 볼까?',
  title: '조건에 맞는 작품을 골라드릴게요',
  description: '보고 싶은 방식만 정하면 Jimmyflix가 후보를 좁혀줍니다.',
  mediaType: '콘텐츠',
  movie: '영화',
  tv: 'TV 프로그램',
  genre: '장르',
  anyGenre: '모든 장르',
  runtime: '최대 러닝타임',
  anyRuntime: '제한 없음',
  minutes: (value: number) => `${value}분 이하`,
  provider: 'OTT',
  anyProvider: '모든 OTT',
  rating: '최소 평점',
  anyRating: '제한 없음',
  ratingValue: (value: number) => `${value}점 이상`,
  sort: '정렬',
  popular: '인기순',
  rated: '평점순',
  recent: '최신순',
  apply: '후보 찾기',
  picksTitle: '먼저 고른 세 작품',
  picksDescription: '조건에 맞는 작품 중 바로 고르기 좋은 후보입니다.',
  reroll: '다른 후보 보기',
  excludeWatched: '봤어요 작품 제외',
  allMatches: '조건에 맞는 전체 작품',
  resultCount: (count: number) => `${count}개를 찾았습니다`,
  emptyTitle: '조건에 맞는 작품이 없습니다',
  emptyDescription: '장르나 평점 조건을 조금 넓혀보세요.',
  regionLabel: (region: Region) => `시청 국가: ${region === 'KR' ? '대한민국' : '미국'}`,
  justWatch: '시청 가능 정보 제공: JustWatch',
  loadingPicks: '추천 후보 준비 중',
} : {
  metadataTitle: 'Find by preferences',
  metadataDescription: 'Combine streaming services, genres, runtime, and ratings to find your next movie or TV show.',
  eyebrow: 'What should I watch?',
  title: 'Let’s narrow down your next watch',
  description: 'Choose how you want to watch and Jimmyflix will make the shortlist.',
  mediaType: 'Type',
  movie: 'Movies',
  tv: 'TV shows',
  genre: 'Genre',
  anyGenre: 'Any genre',
  runtime: 'Maximum runtime',
  anyRuntime: 'Any length',
  minutes: (value: number) => `${value} minutes or less`,
  provider: 'Streaming service',
  anyProvider: 'Any service',
  rating: 'Minimum rating',
  anyRating: 'Any rating',
  ratingValue: (value: number) => `${value}+`,
  sort: 'Sort by',
  popular: 'Popularity',
  rated: 'Rating',
  recent: 'Newest',
  apply: 'Find titles',
  picksTitle: 'Three picks to start with',
  picksDescription: 'A short list from the titles matching your preferences.',
  reroll: 'Show different picks',
  excludeWatched: 'Exclude watched titles',
  allMatches: 'All matching titles',
  resultCount: (count: number) => `${count} titles found`,
  emptyTitle: 'No titles match these preferences',
  emptyDescription: 'Try widening the genre or rating filters.',
  regionLabel: (region: Region) => `Watch region: ${region === 'KR' ? 'South Korea' : 'United States'}`,
  justWatch: 'Availability data provided by JustWatch',
  loadingPicks: 'Preparing recommendations',
}
